spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    username: postgres
    password: my@62post67
  config:
    import: optional:configserver:http://config-server:8888

jwt:
  secret: mySuperSecretKeyForJwtAuthentication123456789