server:
  port: 8083

spring:
  application:
    name: CREDIT-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/credit_service
    username: postgres
    password: my@62post67

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    instances:
      customerService:
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
